config setup

conn %default
    keyexchange=ikev1
    authby=secret
    left=127.0.0.1
    leftid=127.0.0.1
    right=%any
    rightid=%any
    type=transport
    auto=add

conn ikev1-main
    ike=aes256-sha1-modp2048,aes256-sha256-modp2048,aes256-sha512-modp2048,aes128-sha1-modp2048,aes256-sha256-ecp521!
    aggressive=no

conn ikev1-agg
    ike=aes256-sha1-modp2048,aes256-sha256-modp2048,aes256-sha512-modp2048,aes256-sha256-ecp521!
    aggressive=yes

conn ikev2-psk
    keyexchange=ikev2
    authby=secret
    left=127.0.0.1
    leftid=127.0.0.1
    right=%any
    rightid=%any
    type=transport
    auto=add
    ike=aes256-sha256-prfsha256-modp2048,aes256-sha1-prfsha1-modp2048,aes256gcm16-prfsha256-modp2048!

conn ikev2-psk-gcm
    keyexchange=ikev2
    authby=secret
    left=127.0.0.1
    leftid=127.0.0.1
    right=%any
    rightid=%any
    type=transport
    auto=add
    ike=aes256gcm16-prfsha256-modp2048!

conn ikev2-gcm-sha512
    keyexchange=ikev2
    authby=secret
    left=127.0.0.1
    leftid=127.0.0.1
    right=%any
    rightid=%any
    type=transport
    auto=add
    ike=aes256gcm16-prfsha512-ecp521!
