charon {
    interfaces_use = lo
    i_dont_care_about_security_and_use_aggressive_mode_psk = yes
    filelog {
        stderr {
            time_format = %T
            ike_name = yes
            default = 2
            ike = 3
            enc = 2
        }
    }
}
